### ISSUE TITLE
ExecJS::RuntimeError on navigating to home page

### ISSUE THREAD

**Issue by L33tH4x0r** [wacaw/helpdesk#2]
Hi!

Just downloaded the app, it looks promising. The only thing is that I get this error when I try to navigate to my root_path for my website

CssSyntaxError: /var/lib/gems/2.3.0/gems/helpdesk-0.0.40/app/assets/stylesheets/helpdesk/custom.css:3:34: Missed semicolon
// They will automatically be included in application.css.
// You can use Sass (SCSS) here: http://sass-lang.com/

on 
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

in the application .html.erb. I have a pretty custom Devise setup where I use 3 different users, one of which is an admin class. I'm wondering what steps I should try to debug this? I'm new to rails, and I can't find anything else on the internet for this

**Comment by wacaw** [comment]
Hi! 
This commit https://github.com/wacaw/helpdesk/commit/06820a3ff9ba92df0291ed46799b40b33312e762 should solve this problem. 
Try with new 0.0.41 version.

**Comment by L33tH4x0r** [comment]
That fixed the error thanks! 

But now I've got something new, it says that the template is missing. I get the following error
`Missing template helpdesk/tickets/index, helpdesk/application/index, application/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. 
`

**Comment by L33tH4x0r** [comment]
don't worry about it, due to how I build my app I don't think this is gunna work. I built my own, but thanks for posting!

**Comment by wacaw** [comment]
Try this: https://github.com/wacaw/helpdesk-demo
